# scripts/08_regenerate_stage2_figures.py
"""
Regenerates Stage 2 summary figures using the VERIFIED 2023-2024 historical data.
This ensures all public-facing visualizations reflect the corrected, conservative figures.
"""
import polars as pl
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# Constants from verified calculations
VOLUME_TWH_2YR = 3.53
VOLUME_TWH_ANNUALIZED = 1.76
COST_PROXY_GBP_PER_MWH = 164.89
CEILING_GBP_ANNUALIZED = 291_000_000  # ~£291M

print("=" * 80)
print("REGENERATING STAGE 2 FIGURES WITH VERIFIED 2023-2024 DATA")
print("=" * 80)

# 1. Load the clean, verified EVENT DURATION data (generated by script 03)
# This file contains the grouped events with the 'duration_hours' column.
parquet_path = Path("data/processed/03_constraint_event_durations.parquet")
if not parquet_path.exists():
    print("❌ ERROR: 03_constraint_event_durations.parquet not found. Please run scripts/03_p10_event_duration_analysis.py first.")
    exit()

df = pl.read_parquet(parquet_path)
durations = df["duration_hours"].to_numpy()

print(f"✅ Loaded {len(df)} verified historical constraint events.")

# Ensure output directory exists
out_dir = Path("figures")
out_dir.mkdir(parents=True, exist_ok=True)

# ==============================================================================
# FIGURE 1: 05_duration_compatibility.png
# (Shows the clean event duration distribution with handoff/battery targets)
# ==============================================================================
print("\nGenerating 05_duration_compatibility.png...")
fig, ax = plt.subplots(1, 1, figsize=(10, 6))

bins = np.arange(0.5, 12.5, 0.5)
ax.hist(durations, bins=bins, edgecolor='black', color='#2E86AB', alpha=0.8)

# Add vertical lines for key thresholds
ax.axvline(x=1.0, color='#F18F01', linestyle='--', linewidth=2, label='1.0h IT Handoff Target')
ax.axvline(x=2.0, color='#A23B72', linestyle='-.', linewidth=2, label='2.0h Battery Duration')

# Annotate percentiles
p10, p50, p90 = np.percentile(durations, [10, 50, 90])
ax.text(p10, ax.get_ylim()[1]*0.9, f'P10\n({p10:.1f}h)', ha='center', va='bottom', fontsize=9, color='red')
ax.text(p50, ax.get_ylim()[1]*0.85, f'P50\n({p50:.1f}h)', ha='center', va='bottom', fontsize=9, color='black')
ax.text(p90, ax.get_ylim()[1]*0.8, f'P90\n({p90:.1f}h)', ha='center', va='bottom', fontsize=9, color='blue')

ax.set_xlabel('Event Duration (Hours)', fontsize=11)
ax.set_ylabel('Number of Events', fontsize=11)
ax.set_title('Scottish Constraint Event Duration Distribution (Verified 2023-2024)', fontsize=12, fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig(out_dir / "05_duration_compatibility.png", dpi=300, bbox_inches='tight')
print("  ✅ Saved to figures/05_duration_compatibility.png")

# ==============================================================================
# FIGURE 2: 05_theoretical_vs_real_capture.png
# (Visualizes the £291M ceiling vs. realistic capture after friction costs)
# ==============================================================================
print("\nGenerating 05_theoretical_vs_real_capture.png...")
fig, ax = plt.subplots(1, 1, figsize=(8, 5))

# Estimated realistic capture (e.g., 30-40% of ceiling due to P10 incompatibility & friction)
realistic_capture = CEILING_GBP_ANNUALIZED * 0.35  

categories = ['Theoretical Upper Bound\n(Perfect Dispatch)', 'Estimated Real Capture\n(After Friction & P10 Loss)']
values = [CEILING_GBP_ANNUALIZED / 1e6, realistic_capture / 1e6]
colors = ['#A23B72', '#2E86AB']

bars = ax.bar(categories, values, color=colors, edgecolor='black', linewidth=1.2)

# Add value labels on bars
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, yval + 10, f'£{yval:.0f}M/yr', 
            ha='center', va='bottom', fontsize=11, fontweight='bold')

ax.set_ylabel('Annual Constraint Value (£ Millions)', fontsize=11)
ax.set_title('Constraint Value Capture: Theoretical vs. Realistic', fontsize=12, fontweight='bold')
ax.set_ylim(0, max(values) * 1.3)

# Add a note at the bottom
fig.text(0.5, 0.05, 
         "Note: Real capture is materially lower due to AI-operator friction costs \n"
         "(checkpoint overhead, idle GPU amortization) and physical incompatibility \n"
         "with short-duration (<1hr) P10 events.", 
         ha='center', fontsize=9, style='italic', color='dimgray')

plt.tight_layout(rect=[0, 0.15, 1, 1]) # Make room for the bottom text
plt.savefig(out_dir / "05_theoretical_vs_real_capture.png", dpi=300, bbox_inches='tight')
print("  ✅ Saved to figures/05_theoretical_vs_real_capture.png")

# ==============================================================================
# FIGURE 3: 05_cost_proxy_methodology.png
# (A clean visual summary of the corrected calculation methodology)
# ==============================================================================
print("\nGenerating 05_cost_proxy_methodology.png...")
fig, ax = plt.subplots(1, 1, figsize=(9, 6))
ax.axis('off')

methodology_text = (
    "VERIFIED METHODOLOGY: Scottish Constraint Volume & Cost Proxy (2023-2024)\n\n"
    "1. DATA SOURCE: NESO Day Ahead Constraint Flows (SCOTEX & SSEN-S boundaries)\n"
    "2. HISTORICAL FILTER: Strictly limited to 2023–2024 outturn data.\n"
    "   (Excludes all future Day-Ahead forecast artifacts)\n"
    "3. EVENT IDENTIFICATION: Isolated half-hours where Flow (MW) > Limit (MW).\n"
    "   → Result: 3,804 constraint half-hours over 2 years.\n"
    "4. VOLUME CALCULATION: Summed differential (Flow - Limit) for event half-hours only.\n"
    f"   → Verified 2-Year Volume: {VOLUME_TWH_2YR} TWh\n"
    f"   → Annualized Volume: ~{VOLUME_TWH_ANNUALIZED} TWh/year\n"
    "5. COST PROXY: Applied GB-wide average constraint cost.\n"
    f"   → Proxy: £{COST_PROXY_GBP_PER_MWH}/MWh\n"
    "6. THEORETICAL CEILING:\n"
    f"   → {VOLUME_TWH_ANNUALIZED} TWh/yr × £{COST_PROXY_GBP_PER_MWH}/MWh = ~£{CEILING_GBP_ANNUALIZED/1e6:.0f} Million / year\n\n"
    "⚠️ CAVEAT: This is a theoretical upper bound. Real-world capture will be \n"
    "materially lower due to AI-operator friction costs and the physical \n"
    "incompatibility of short-duration (P10) events."
)

ax.text(0.05, 0.95, methodology_text, fontsize=11, family='monospace', 
        verticalalignment='top', bbox=dict(boxstyle='round,pad=1', facecolor='#f4f4f4', edgecolor='#cccccc'))

plt.savefig(out_dir / "05_cost_proxy_methodology.png", dpi=300, bbox_inches='tight')
print("  ✅ Saved to figures/05_cost_proxy_methodology.png")

print("\n" + "=" * 80)
print("ALL STAGE 2 FIGURES SUCCESSFULLY REGENERATED WITH VERIFIED DATA")
print("=" * 80)